//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Counter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultStoragePath {
            get {
                return ((string)(this["DefaultStoragePath"]));
            }
            set {
                this["DefaultStoragePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name (Original Name)")]
        public string PartStart {
            get {
                return ((string)(this["PartStart"]));
            }
            set {
                this["PartStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PollStart {
            get {
                return ((string)(this["PollStart"]));
            }
            set {
                this["PollStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string CSVDelimiter {
            get {
                return ((string)(this["CSVDelimiter"]));
            }
            set {
                this["CSVDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bellefontaine Congregation\'s Weekly Meetings Please have your Name displayed to e" +
            "nter meeting")]
        public string PollDateFinder {
            get {
                return ((string)(this["PollDateFinder"]));
            }
            set {
                this["PollDateFinder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bellefontaine Congregation")]
        public string CongregationName {
            get {
                return ((string)(this["CongregationName"]));
            }
            set {
                this["CongregationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bellefontainecongregation@gmail.com")]
        public string CongregationEmail {
            get {
                return ((string)(this["CongregationEmail"]));
            }
            set {
                this["CongregationEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DelimterReplacement {
            get {
                return ((string)(this["DelimterReplacement"]));
            }
            set {
                this["DelimterReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Folder {
            get {
                return ((string)(this["Folder"]));
            }
            set {
                this["Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,User_Name,User_Email,Date/Time,Poll_Message,Poll_Count")]
        public string PollLayout {
            get {
                return ((string)(this["PollLayout"]));
            }
            set {
                this["PollLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DateIndex {
            get {
                return ((decimal)(this["DateIndex"]));
            }
            set {
                this["DateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("name,gender,address,home_phone,mobile_phone,work_phone,email,elder,ministerial_se" +
            "rvant,years_appointed,age,years_baptized,unbaptized_publisher,pioneer,aux_pionee" +
            "r,special_pioneer,missionary,deaf,blind,infirm,group_overseer")]
        public string KHSSettings {
            get {
                return ((string)(this["KHSSettings"]));
            }
            set {
                this["KHSSettings"] = value;
            }
        }
    }
}
